### PR TITLE
upgraded to 2.24.2

### PR DESCRIPTION
**Pull request by krishnaglodha**
* Upgraded GeoServer from version 2.24.1 to 2.24.2

* upgrade version in action

following similar commits as https://github.com/kartoza/docker-geoserver/commit/7cd061414ae84e8921c404dd2410ec539d35b4a9

### CODE REVIEW

**Review by NyakudyaA — COMMENTED** [review]
@krishnaglodha It might also be worthwhile to check if there are plugins that have been demoted/promoted from stable/community plugins. I know we can still download them on runtime but to package them nicely would be the first choice.

**Comment by krishnaglodha** [comment]
> @krishnaglodha It might also be worthwhile to check if there are plugins that have been demoted/promoted from stable/community plugins. I know we can still download them on runtime but to package them nicely would be the first choice.

I'll have a quick look at stable/community plugin list from 2.24.1 and 2.24.2  and let you know here

**Comment by BRMeaf75** [comment]
Hey @NyakudyaA I'm trying to deploy a geoserver with the clustering enabled (using the internal broker) but my geoservers just doesn't stop to crash without any reason after receiving some requests do you have any contact details or some way to reach you, we would like get some help from some expert from geoserver/kartoza

**Comment by krishnaglodha** [comment]
> Hey @NyakudyaA I'm trying to deploy a geoserver with the clustering enabled (using the internal broker) but my geoservers just doesn't stop to crash without any reason after receiving some requests do you have any contact details or some way to reach you, we would like get some help from some expert from geoserver/kartoza

Hi, can you please post some screenshots or error logs to check

**Comment by krishnaglodha** [comment]
> @krishnaglodha It might also be worthwhile to check if there are plugins that have been demoted/promoted from stable/community plugins. I know we can still download them on runtime but to package them nicely would be the first choice.

It looks okay, I checked `sourceforge` site and plugin directory looks the same

**Comment by NyakudyaA** [comment]
> Hey @NyakudyaA I'm trying to deploy a geoserver with the clustering enabled (using the internal broker) but my geoservers just doesn't stop to crash without any reason after receiving some requests do you have any contact details or some way to reach you, we would like get some help from some expert from geoserver/kartoza

Please get in touch https://kartoza.erpnext.com/product/support

**Review by NyakudyaA — APPROVED** [review]

**Comment by krishnaglodha** [comment]
@NyakudyaA , How long will take to have the image in docker hub?

**Pull request merged**
