### PR TITLE
[WIP] Make the image helm-chart friendly

### PR DESCRIPTION
**Pull request by lucernae**
Related with this ticket: #348

### CODE REVIEW

**Comment by lucernae** [comment]
It seems, the action failed to start due to the cache size is too huge.

**Comment by lucernae** [comment]
Immediately use 2.20.2 per this suggestion: https://github.com/kartoza/docker-geoserver/issues/353

**Comment by NyakudyaA** [comment]
> Immediately use 2.20.2 per this suggestion: https://github.com/kartoza/docker-geoserver/issues/353

I would revert this to use version 2.20.1 so that you can merge this. We are not sure when 2.20.2 will be available. It could take months

**Comment by NyakudyaA** [comment]
@lucernae can we get this merged. We now have 2.20.2 officially released

**Comment by lucernae** [comment]
@NyakudyaA I think the build test all completed. Can you try published pr images?

**Comment by NyakudyaA** [comment]
> @NyakudyaA I think the build test all completed. Can you try published pr images?

thanks @lucernae Will test them now and revert

**Comment by NyakudyaA** [comment]
> > @NyakudyaA I think the build test all completed. Can you try published pr images?
> 
> thanks @lucernae Will test them now and revert

They are a bunch of errors coming up with the images. 
merge-status

Can you maybe try to merge master into your repo and see if it fixes these errors

**Pull request merged**
