### PR TITLE
added docs from krishnaglodha

### PR DESCRIPTION
**Pull request by NyakudyaA**
supersedes https://github.com/kartoza/docker-geoserver/pull/485
Credits go to @krisaoe

### CODE REVIEW

**Comment by krishnaglodha** [comment]
Hi @NyakudyaA , thanks for merging, should we host statics docs somewhere and link in in Readme ?

**Comment by NyakudyaA** [comment]
Yes, I think so, Maybe we can host the docs with GitHub pages. What's your suggestion here

**Comment by krishnaglodha** [comment]
I haven't hosted with GH pages yes.. Are we looking to connect it with kartoza.com domain ? Then we can host on Kartoza's hosting

**Comment by NyakudyaA** [comment]
I will ask how to do it from Kartoza side and revert to you

**Comment by NyakudyaA** [comment]
Hi @krishnaglodha Can you please share the generated markdown files (.md) so that we can use those for the docs. We are currently using the static HTML files that were generated but it will be difficult to maintain as we would have to update the HTML files and we can also automate the building docs with GitHub actions

**Pull request merged**
